name: food_app
description: "A Food app with flutter"

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  provider: ^6.1.2
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  collection: ^1.18.0
  flutter_credit_card: ^4.0.1
  intl: ^0.19.0
  firebase_core: ^2.27.2
  firebase_auth: ^4.18.0
  firebase_storage: ^11.6.11
  cloud_firestore: ^4.15.10

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/burgers/
    - assets/Sides/
    - assets/drinks/
    - assets/salads/
    - assets/deserts/
